# This is a basic workflow to help you get started with Actions

name: Test Action Idea

# Controls when the workflow will run
on:
  workflow_dispatch
    
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_test_suite:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: GitHub API Request
        uses: octokit/request-action@v2.1.0
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: sfingram
          repo: testchecks
          name: "Snarf"
          head_sha: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
