# This workflow is part of the POC to branch protection with manual control

name: POC Test Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# because we're triggering this with each push, we don't want to accrue a long list of queued runs 
# this directive will cancel other workflow runs for this branch
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  faststuff:
    runs-on: ubuntu-latest
    steps:
      - name: Run a fast thing
        run: echo Passed faststuff

  # This workflow contains a single job called "build"
  slowstuff:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # add an environment (this is the trick to manually controlling the job)
    environment: test
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a slow thing
        run: |
          sleep 10
          echo Passed slowstuff
